apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stashcache-origin-ncsa-des
  namespace: osg
  labels: 
    k8s-app: stashcache-origin-ncsa-des
spec:
  template:
    metadata: 
      labels:
        k8s-app: stashcache-origin-ncsa-des
    spec:
      hostNetwork: true
      nodeSelector: 
        kubernetes.io/hostname: desdev1.cosmology.illinois.edu
      containers:
      - name: stashcache-origin
        image: opensciencegrid/stash-origin:development
        imagePullPolicy: Always
        #command: ["sh", "-c", "sleep infinity"]
        env:
        - name : XC_SITENAME
          value: NCSA-DES-Origin
        - name: XC_ROOTDIR
          value: /stashdata
        - name: XC_ORIGINEXPORT
          value: /desdm
        volumeMounts:
          - name: config10
            mountPath: /etc/xrootd/config.d/10-origin-authfile.cfg
            subPath: 10-origin-authfile.cfg
          - name: configpubauth
            mountPath: /etc/xrootd/public-origin-authfile
            subPath: public-origin-authfile
          - name: gpfsdata
            mountPath: /stashdata/desdm
            readOnly: true
      volumes:
        - name: config10
          configMap:
            name: stashcache-origin-config-ncsa-des
            items:
               - key: 10-origin-authfile.cfg
                 path: 10-origin-authfile.cfg
        - name: configpubauth
          configMap:
            name: stashcache-origin-config-ncsa-des
            items:
               - key: public-origin-authfile
                 path: public-origin-authfile
        - name: gpfsdata
          hostPath: 
            path: /des008/cluster_scratch/users/osg
            type: Directory 

