apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stashcache-origin-merra2
  namespace: osg
  labels: 
    k8s-app: stashcache-origin-merra2
spec:
  template:
    metadata: 
      labels:
        k8s-app: stashcache-origin-merra2
    spec:
      containers:
      - name: stashcache-origin-merra2
        image: sfiligoi/prp-stashcache-origin
        imagePullPolicy: Always
        #command: ["sh", "-c", "sleep infinity"]
        env:
        - name: EXPORTDATA
          value: /edex/merra2
        volumeMounts:
          - name: config10o
            mountPath: /etc/xrootd/config.d/10-origin-site-local.cfg
            subPath: 10-origin-site-local.cfg
            readOnly: true
          - name: config10c
            mountPath: /etc/xrootd/config.d/10-common-site-local.cfg
            subPath: 10-common-site-local.cfg
            readOnly: true
          - name: config20
            mountPath: /etc/xrootd/config.d/20-network-setup.cfg
            subPath: 20-network-setup.cfg
            readOnly: true
          - name: configpubauth
            mountPath: /etc/xrootd/public-origin-authfile
            subPath: public-origin-authfile
            readOnly: true
          - name: fs-store
            mountPath: /edex
            readOnly: true
      volumes:
        - name: config10o
          configMap:
            name: stashcache-origin-merra2-config
            items:
               - key: 10-origin-site-local.cfg
                 path: 10-origin-site-local.cfg
        - name: config10c
          configMap:
            name: stashcache-origin-merra2-config
            items:
               - key: 10-common-site-local.cfg
                 path: 10-common-site-local.cfg
        - name: config20
          configMap:
            name: stashcache-origin-merra2-config
            items:
               - key: 20-network-setup.cfg
                 path: 20-network-setup.cfg
        - name: configpubauth
          configMap:
            name: stashcache-origin-merra2-config
            items:
               - key: public-origin-authfile
                 path: public-origin-authfile
        - name: fs-store
          flexVolume:
            driver: ceph.rook.io/rook
            fsType: ceph
            options:
              clusterNamespace: rook
              fsName: nautilusfs
              path: /edex
              mountUser: edex
              mountSecret: ceph-fs-secret          

