apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stashcache-origin-merra2
  namespace: osg
  labels: 
    k8s-app: stashcache-origin-merra2
spec:
  template:
    metadata: 
      labels:
        k8s-app: stashcache-origin-merra2
    spec:
      containers:
      - name: stashcache-origin-merra2
        image: opensciencegrid/stash-origin:development
        imagePullPolicy: Always
        #command: ["sh", "-c", "sleep infinity"]
        env:
        - name: XC_ROOTDIR
          value: /edex
        - name : XC_SITENAME
          value: SDSC-MERRA2-Origin
        volumeMounts:
          - name: config10o
            mountPath: /etc/xrootd/config.d/10-origin-site-local.cfg
            subPath: 10-origin-site-local.cfg
          - name: config20
            mountPath: /etc/xrootd/config.d/20-network-setup.cfg
            subPath: 20-network-setup.cfg
          - name: configpubauth
            mountPath: /etc/xrootd/public-origin-authfile
            subPath: public-origin-authfile
          - name: configinit
            mountPath: /usr/local/sbin/xcache_pod_init.sh
            subPath: xcache_pod_init.sh
          - name: fs-store
            mountPath: /edex
            readOnly: true
      volumes:
        - name: config10o
          secret:
            secretName: stashcache-origin-merra2-config
            items:
               - key: 10-origin-site-local.cfg
                 path: 10-origin-site-local.cfg
            defaultMode: 292
        - name: config20
          secret:
            secretName: stashcache-origin-merra2-config
            items:
               - key: 20-network-setup.cfg
                 path: 20-network-setup.cfg
            defaultMode: 292
        - name: configpubauth
          secret:
            secretName: stashcache-origin-merra2-config
            items:
               - key: public-origin-authfile
                 path: public-origin-authfile
            defaultMode: 292
        - name: configinit
          secret:
            secretName: stashcache-origin-merra2-config
            items:
               - key: xcache_pod_init.sh
                 path: xcache_pod_init.sh
            defaultMode: 365
        - name: fs-store
          flexVolume:
            driver: ceph.rook.io/rook
            fsType: ceph
            options:
              clusterNamespace: rook
              fsName: nautilusfs
              path: /edex
              mountUser: edex
              mountSecret: ceph-fs-secret          

